# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     snippet: studio-rpc-usb-uart
#     cmake-args: -DCONFIG_ZMK_STUDIO=y
#     artifact-name: corne_left_with_studio
#
---
include:
  # Corne Dongle Firmware
  - board: seeeduino_xiao_ble
    shield: corne_dongle dongle_screen
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000
    artifact-name: corne_dongle

  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view_battery
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_ZMK_SPLIT=y
    artifact-name: corne_dongle_left

  - board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_view_battery
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_ZMK_SPLIT=y
    artifact-name: corne_dongle_right

  # Corne BT firmware
  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view_battery
    snippet: studio-rpc-usb-uart
    artifact-name: corne_bt_left
  - board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_view_battery
    artifact-name: corne_bt_right

  # reset_settings
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: nano_reset

  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: xiao_reset
  
  # Lily BT firmware
  - board: nice_nano_v2
    shield: lily58_left nice_view_adapter nice_view_battery
    snippet: studio-rpc-usb-uart
    artifact-name: lily58_bt_left

  - board: nice_nano_v2
    shield: lily58_right nice_view_adapter nice_view_battery
    artifact-name: lily58_bt_right
